TransCareToday/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using TransCareToday.Models;
using TransCareToday.ViewModels.TableView;

namespace TransCareToday.Controllers
{
    public class ProvidersController : Controller
    {
        private readonly TransCareTodayContext _context;

        public ProvidersController(TransCareTodayContext context)
        {
            _context = context;
        }
		
		public async Task<IActionResult> Index(int? pageIndex, int? pageSize, int? oldPageSize, string sortColumnsJson, string filterColumnsJson)
		{
			var providers = _context.Providers;

			pageIndex = pageIndex ?? 1;

			if (pageSize.HasValue && oldPageSize.HasValue && pageSize != oldPageSize)
			{
				int rowIndex = (pageIndex.Value - 1) * oldPageSize.Value;
				pageIndex = rowIndex / pageSize.Value + 1;
			}

			var parameters = new TableViewParameters
			{
				PageIndex = pageIndex.Value,
				PageSize = pageSize ?? 10
			};

			List<SortColumn> sortColumns = null;
			try { sortColumns = JsonConvert.DeserializeObject<List<SortColumn>>(sortColumnsJson); } catch { }
			if (sortColumns != null) parameters.SortColumns.AddRange(sortColumns);

			List<FilterColumn> filterColumns = null;
			try { filterColumns = JsonConvert.DeserializeObject<List<FilterColumn>>(filterColumnsJson); } catch { }
			if (filterColumns != null) parameters.FilterColumns.AddRange(filterColumns);

			return View(await providers.ToTableView(parameters));
		}

		// GET: Providers/Details/5
		public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers
                .FirstOrDefaultAsync(m => m.ProviderId == id);
            if (provider == null)
            {
                return NotFound();
            }

            return View(provider);
        }

        // GET: Providers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Providers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProviderId,IsInactive,IsAcceptingNewPatients,Name,Description,AddressLine1,AddressLine2,AddressLine3,City,State,ZipCode,SearchVector")] Provider provider)
        {
            if (ModelState.IsValid)
            {
                provider.ProviderId = Guid.NewGuid();
                _context.Add(provider);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(provider);
        }

        // GET: Providers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers.FindAsync(id);
            if (provider == null)
            {
                return NotFound();
            }
            return View(provider);
        }

        // POST: Providers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ProviderId,IsInactive,IsAcceptingNewPatients,Name,Description,AddressLine1,AddressLine2,AddressLine3,City,State,ZipCode,SearchVector")] Provider provider)
        {
            if (id != provider.ProviderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(provider);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProviderExists(provider.ProviderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(provider);
        }

        // GET: Providers/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers
                .FirstOrDefaultAsync(m => m.ProviderId == id);
            if (provider == null)
            {
                return NotFound();
            }

            return View(provider);
        }

        // POST: Providers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var provider = await _context.Providers.FindAsync(id);
            _context.Providers.Remove(provider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProviderExists(Guid id)
        {
            return _context.Providers.Any(e => e.ProviderId == id);
        }
    }
}

TransCareToday/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Trans Care Today</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/lib/jqueryui/jquery-ui.css" />
		<link rel="stylesheet" href="~/css/site.css" />
		<link rel="stylesheet" href="~/css/survey.css" />
		<link rel="stylesheet" href="~/css/arrows.css" />
		<link rel="stylesheet" href="~/css/pagination.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Trans Care Today</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Providers" asp-action="Index">Find a provider</a></li>
				</ul>
				<partial name="_LoginPartial" />
			</div>
		</div>
	</nav>

	<partial name="_CookieConsentPartial" />

	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2018 - Trans Care Today</p>
			<ul>
				<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
				<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
				<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
			</ul>
		</footer>
	</div>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/jqueryui/jquery-ui.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/base64-arraybuffer.js" asp-append-version="true"></script>
		<script src="~/js/lockbox.js" asp-append-version="true"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
		<script src="~/js/survey.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.12.1/jquery-ui.min.js"
				asp-fallback-src="~/lib/jqueryui/jquery-ui.min.js"
				asp-fallback-test="window.jQuery.ui"
				crossorigin="anonymous"
				integrity="sha384-Dziy8F2VlJQLMShA6FHWNul/veM9bCkRUaLqr199K94ntO5QUrLJBEbYegdSkkqX">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>
	@if (SignInManager.IsSignedIn(User))
	{
		<script>
			var lockbox = loadLockbox();
		</script>
	}
	else
	{
		<script>
			clearLockbox();
		</script>
	}


	@RenderSection("Scripts", required: false)
</body>
</html>

TransCareToday/Views/Shared/_SortableHeader.cshtml
@using TransCareToday.ViewModels.TableView
@model TableViewColumn

@{
	var cols = Model.Parameters.SortColumns;
	var direction = cols.Any() && cols.First().Column == Model.Column
		? cols.First().Descending ? "down-arrow" : "up-arrow"
		: "";
}

<th>
	<a asp-route-pageIndex="@(Model.Parameters.PageIndex)"
	   asp-route-pageSize="@(Model.Parameters.PageSize)"
	   asp-route-sortColumnsJson="@Json.Serialize(Model.Parameters.SortColumns.SortBy(Model.Column))"
	   asp-route-filterColumnsJson="@Json.Serialize(Model.Parameters.FilterColumns)"
	   class="sort @direction">@Model.Display</a>
</th>